In [35]:
from ecostyles import EcoStyles
# Create styles instance
styles = EcoStyles()

import altair as alt
import pandas as pd

In [36]:
# Register and enable a theme
styles.register_and_enable_theme(theme_name="article")

In [37]:
styles.eco_colours

{'red': '#e6224b',
 'blue-light': '#179fdb',
 'blue-dark': '#122b39',
 'yellow': '#f4c245',
 'orange': '#eb5c2e',
 'turquoise': '#36b7b4'}

In [38]:
# Load average electricity data (excl CCL)
elec_excl_df = pd.read_excel('elec_uk_non-dom.xlsx', skiprows=6, sheet_name='3.4.1 (excl CCL)')
elec_excl_df = elec_excl_df[['Year', 'Quarter', 'Electricity: Average (Pence per kWh)']]
elec_excl_df = elec_excl_df.rename(columns={'Electricity: Average (Pence per kWh)': 'Electricity excl CCL'})
elec_excl_df['Quarter'] = elec_excl_df['Quarter'].str.replace(r'(st|nd|rd|th)$', '', regex=True)
elec_excl_df

    Year Quarter  Electricity excl CCL
0   2004       1              3.724000
1   2004       2              3.593000
2   2004       3              3.663000
3   2004       4              4.456000
4   2005       1              4.572000
..   ...     ...                   ...
82  2024       3             25.147581
83  2024       4             24.975982
84  2025       1             25.334168
85  2025       2             23.675360
86  2025       3             22.955889

[87 rows x 3 columns]

In [39]:
# Load average electricity data (incl CCL)
elec_incl_df = pd.read_excel('elec_uk_non-dom.xlsx', skiprows=6, sheet_name='3.4.2 (incl CCL)')
elec_incl_df = elec_incl_df[['Year', 'Quarter', 'Electricity: Average (Pence per kWh)']]
elec_incl_df = elec_incl_df.rename(columns={'Electricity: Average (Pence per kWh)': 'Electricity incl CCL'})
elec_incl_df['Quarter'] = elec_incl_df['Quarter'].str.replace(r'(st|nd|rd|th)$', '', regex=True)
elec_incl_df

    Year Quarter  Electricity incl CCL
0   2004       1              4.015000
1   2004       2              3.887000
2   2004       3              3.946000
3   2004       4              4.742000
4   2005       1              4.845000
..   ...     ...                   ...
82  2024       3             25.669576
83  2024       4             25.503655
84  2025       1             25.867873
85  2025       2             24.198340
86  2025       3             23.470173

[87 rows x 3 columns]

In [40]:
# Merge and reformat dataframes
avg_elec_df = elec_excl_df.merge(elec_incl_df, on=['Year','Quarter'], how='outer')
avg_elec_df = avg_elec_df.melt(
    id_vars = ['Year', 'Quarter'],
    value_vars = ['Electricity excl CCL', 'Electricity incl CCL'],
    var_name = 'Type',
    value_name = 'Electricity'
)
avg_elec_df = avg_elec_df.sort_values(['Year', 'Quarter'])
avg_elec_df['Period'] = 'Q' + avg_elec_df['Quarter'].astype(str) + ' ' + avg_elec_df['Year'].astype(str)
avg_elec_df

     Year Quarter                  Type  Electricity   Period
0    2004       1  Electricity excl CCL     3.724000  Q1 2004
87   2004       1  Electricity incl CCL     4.015000  Q1 2004
1    2004       2  Electricity excl CCL     3.593000  Q2 2004
88   2004       2  Electricity incl CCL     3.887000  Q2 2004
2    2004       3  Electricity excl CCL     3.663000  Q3 2004
..    ...     ...                   ...          ...      ...
171  2025       1  Electricity incl CCL    25.867873  Q1 2025
85   2025       2  Electricity excl CCL    23.675360  Q2 2025
172  2025       2  Electricity incl CCL    24.198340  Q2 2025
86   2025       3  Electricity excl CCL    22.955889  Q3 2025
173  2025       3  Electricity incl CCL    23.470173  Q3 2025

[174 rows x 5 columns]

In [41]:
# Plot line chart
elec_line_chart = alt.Chart(avg_elec_df).mark_line().encode(
    x = alt.X('Period:N',
              sort=None,
              axis=alt.Axis(
                  values=['Q4 2004', 'Q4 2006', 'Q4 2008', 'Q4 2010', 'Q4 2012', 'Q4 2014', 'Q4 2016', 'Q4 2018', 'Q4 2020', 'Q4 2022', 'Q4 2024'],
                  grid=False,
                  titleFontSize=13,
                  labelFontSize=13
                  )),
    y = alt.Y('Electricity:Q', 
              title = 'Pence per kWh', 
              axis=alt.Axis(
                  titleFontSize=13,
                  labelFontSize=13,
                  grid=False)),
    color = alt.Color('Type:N',
                      legend=alt.Legend(
                          orient='none',
                          legendX=10,
                          legendY=10,
                          padding=10,
                          labelFontSize=13))
).properties(
    width=450,
    height=400
)
styles.add_source(elec_line_chart, 'ONS - Prices of fuels purchased by non-domestic consumers in the UK (2025)')
elec_line_chart

alt.Chart(...)

In [42]:
# Load industrial electricity prices data
iea_elec_df = pd.read_excel('ind_elec_price.xlsx', skiprows=8, sheet_name='5.3.1 (inc. taxes)')
iea_elec_df = iea_elec_df.drop(['UK relative to IEA median%','UK relative to IEA rank','UK relative to G7 rank','Japan','Australia','Netherlands','Denmark'], axis=1)
iea_elec_df = iea_elec_df[iea_elec_df['Year'] == 2024]
iea_elec_df = iea_elec_df.melt(
    id_vars=['Year'],
    var_name='Country',
    value_name='Value'
)
iea_elec_df

    Year         Country      Value
0   2024         Austria  18.161283
1   2024         Belgium  18.140935
2   2024         Finland   8.141674
3   2024          France  16.331674
4   2024         Germany  20.993022
5   2024          Greece  15.242217
6   2024         Ireland  24.768391
7   2024           Italy  23.522087
8   2024      Luxembourg  15.104022
9   2024        Portugal  12.406239
10  2024           Spain  13.251522
11  2024          Sweden    8.79105
12  2024  United Kingdom      26.63
13  2024          Canada   7.426511
14  2024  Czech Republic  20.576917
15  2024         Hungary  18.251994
16  2024           Korea  10.973783
17  2024     New Zealand  11.625782
18  2024          Norway   3.965367
19  2024          Poland  20.036201
20  2024        Slovakia      19.69
21  2024     Switzerland  24.428182
22  2024          Turkey  10.096118
23  2024             USA   6.360009
24  2024      IEA median  15.242217

In [43]:
# Sort countries by value
iea_elec_df = iea_elec_df.sort_values('Value', ascending=False)

# Get countries excluding median
countries = iea_elec_df[iea_elec_df['Country'] != 'IEA median']['Country'].tolist()

# Create sort order: countries (high to low) + gap + median
sort_order = countries + ['___gap1___','___gap2___', 'IEA median']

# Add gap rows
gap_rows = pd.DataFrame({
    'Year': [2024, 2024],
    'Country': ['___gap1___','___gap2___'],
    'Value': [0, 0]
})
iea_elec_df = pd.concat([iea_elec_df, gap_rows], ignore_index=True)

# Create color mapping
color_lookup = {
    'United Kingdom':'#179fdb',
    'IEA median': '#122b39'
}
iea_elec_df['color'] = iea_elec_df['Country'].map(color_lookup).fillna('#B4B4B4')

iea_elec_df

    Year         Country      Value    color
0   2024  United Kingdom      26.63  #179fdb
1   2024         Ireland  24.768391  #B4B4B4
2   2024     Switzerland  24.428182  #B4B4B4
3   2024           Italy  23.522087  #B4B4B4
4   2024         Germany  20.993022  #B4B4B4
5   2024  Czech Republic  20.576917  #B4B4B4
6   2024          Poland  20.036201  #B4B4B4
7   2024        Slovakia      19.69  #B4B4B4
8   2024         Hungary  18.251994  #B4B4B4
9   2024         Austria  18.161283  #B4B4B4
10  2024         Belgium  18.140935  #B4B4B4
11  2024          France  16.331674  #B4B4B4
12  2024          Greece  15.242217  #B4B4B4
13  2024      IEA median  15.242217  #122b39
14  2024      Luxembourg  15.104022  #B4B4B4
15  2024           Spain  13.251522  #B4B4B4
16  2024        Portugal  12.406239  #B4B4B4
17  2024     New Zealand  11.625782  #B4B4B4
18  2024           Korea  10.973783  #B4B4B4
19  2024          Turkey  10.096118  #B4B4B4
20  2024          Sweden    8.79105  #B4B4B4
21  2024         Finland   8.141674  #B4B4B4
22  2024          Canada   7.426511  #B4B4B4
23  2024             USA   6.360009  #B4B4B4
24  2024          Norway   3.965367  #B4B4B4
25  2024      ___gap1___          0  #B4B4B4
26  2024      ___gap2___          0  #B4B4B4

In [44]:
# Plot bar chart
iea_base = alt.Chart(iea_elec_df).encode(
    alt.X('Value:Q').axis(
        title='Pence per kWh',
        labelFontSize=13,
        titleFontSize=13,
        grid=False
    ),
    alt.Y('Country:N').sort(sort_order).axis(
        labelExpr='indexof(datum.label, "___gap") >= 0 ? "" : datum.label',
        labelFontSize=13,
        title='',
        grid=False
    ),
    alt.Color('color:N').scale(None)
)

iea_bars = iea_base.mark_bar().encode(
    opacity=alt.condition(
        'indexof(datum.Country, "___gap") >= 0',
        alt.value(0),
        alt.value(1)
    )
)

iea_text = iea_base.mark_text(
    align='left',
    dx=5,
    fontSize=13,
    text=alt.expr("format(datum.Value, '.1f')")
).encode(
    opacity=alt.condition(
        alt.FieldOneOfPredicate(field='Country', oneOf=list(color_lookup.keys())),
        alt.value(1),
        alt.value(0)
    )
)

iea_bar_chart = (iea_bars + iea_text).properties(
    title=alt.TitleParams(
        ['Source: DESNZ - Industrial electricity prices in the IEA (2024)', 'Note: US prices from EIA and Norway prices from SSB converted to pence using annual average exchange rates'],
        orient='bottom',
        fontStyle='italic',
        fontSize=10,
        color='#676A8680',
        fontWeight='normal',
        frame='group',
        dx=0,
        offset=7
    ),
    width=450,
    height=400
)

iea_bar_chart

alt.LayerChart(...)

In [45]:
# Load sme survey data
sme_barrier_df = pd.read_excel('sme_survey_2024.xlsx', sheet_name='Tables', skiprows=1105, nrows=15)
sme_barrier_df = sme_barrier_df.rename(columns={'Sample size, business type': 'Response'})
sme_barrier_df = sme_barrier_df[['Response', 'Total']]
sme_barrier_df['Response'] = sme_barrier_df['Response'].str.replace(' Col %', '', regex=False)
sme_barrier_df = sme_barrier_df[~sme_barrier_df['Response'].str.contains('Bases', na=False)]
sme_barrier_df = sme_barrier_df[~sme_barrier_df['Response'].isin(['Don\'t know', 'Refused'])]
response_mapping = {
    'You thought you would be rejected': 'Thought would be rejected',
    'You thought it would be too expensive': 'Too expensive',
    "You don't want to take on additional risk": 'Don\'t want additional risk',
    'Now is not the right time because of economic conditions': 'Wrong time due to economy',
    "You didn't know where to find the appropriate finance you needed": 'Unsure where to find finance',
    'Poor credit history': 'Poor credit history',
    'The decision would have taken too long/too much hassle': 'Too long/too much hassle',
    'Bank forms and literature hard to understand': 'Forms hard to understand',
    "You thought you'd be asked to provide too much security": 'Too much security required'
}
sme_barrier_df['Response'] = sme_barrier_df['Response'].replace(response_mapping)
sme_barrier_df = sme_barrier_df.sort_values('Total', ascending=False)
sme_barrier_df

                        Response Total
4     Don't want additional risk    63
3                  Too expensive    60
5      Wrong time due to economy    59
2      Thought would be rejected    34
8       Too long/too much hassle    29
10    Too much security required    28
6   Unsure where to find finance    22
11                         Other    18
9       Forms hard to understand    17
7            Poor credit history    10

In [46]:
# Plot bar chart
sme_barrier_base = alt.Chart(sme_barrier_df).encode(
    y=alt.Y('Response:N',
            sort=None, 
            title='Reasons for not seeking additional finance in last 12 months',
            axis=alt.Axis(
                titleAlign='left',
                titleAnchor='start',
                titleAngle=0,
                titleX=0,
                titleY=-10,
                titleFontSize=13, 
                labelFontSize=13, 
                grid=False)),
    x=alt.X('Total:Q',
            title='Proportion of businesses that needed finance but did not apply',
            axis=alt.Axis(titleFontSize=13, labelExpr='datum.value + "%"', labelFontSize=13, grid=False))
)

sme_barrier_bar = sme_barrier_base.mark_bar()

sme_barrier_text = sme_barrier_base.mark_text(
    align='left',
    dx=5,
    fontSize=13,
    text=alt.expr("format(datum.Total, '.0f') + '%'")
)

sme_barrier_bar_chart = (sme_barrier_bar + sme_barrier_text)

styles.add_source(sme_barrier_bar_chart, 'DBT - Small Business Survey (2024)')
sme_barrier_bar_chart

alt.LayerChart(...)

In [47]:
# Load PNFCs lending to firms data
pnfcs_df = pd.read_csv('firm_lending.csv')
pnfcs_df = pnfcs_df.rename(columns={
    'Date': 'date',
    "Monthly amounts outstanding of monetary financial institutions' sterling loans to (excluding commercial paper) private non-financial corporations (in sterling millions) not seasonally adjusted              [a] [b] [c] [d] [e] [f] [g] [h] [i] [j]             LPMB6NP": 'pnfcs'})
pnfcs_df['date'] = pd.to_datetime(pnfcs_df['date'], format='%d %b %y')
pnfcs_df['year'] = pnfcs_df['date'].dt.year

# Calculate annual average of monthly PNFC lending
pnfcs_annual_df = pnfcs_df.groupby('year')['pnfcs'].mean().reset_index()
pnfcs_annual_df.columns = ['year', 'pnfcs']
pnfcs_annual_df

    year          pnfcs
0   1997  167812.500000
1   1998  171268.333333
2   1999  177936.166667
3   2000  198510.083333
4   2001  222252.666667
5   2002  237096.250000
6   2003  258386.250000
7   2004  271592.666667
8   2005  313206.666667
9   2006  369711.916667
10  2007  424956.166667
11  2008  482378.583333
12  2009  483935.750000
13  2010  450788.416667
14  2011  414224.250000
15  2012  396949.000000
16  2013  375435.333333
17  2014  360163.500000
18  2015  346911.750000
19  2016  352103.000000
20  2017  345769.916667
21  2018  367426.666667
22  2019  389065.583333
23  2020  421944.916667
24  2021  426721.833333
25  2022  428777.000000
26  2023  426918.750000
27  2024  431647.416667
28  2025  456541.250000
29  2026  478163.000000

In [48]:
# Load GDP YBHA data
gdp_df = pd.read_csv('gdp_ybha.csv', skiprows=7)
gdp_df = gdp_df.rename(columns={
    'Important notes': 'year',
    'Following a quality review it has been identified that the methodology used to estimate elements of purchased software within gross fixed capital formation (GFCF) has led to some double counting from 1997 onwards. When this issue is amended in The Blue Book 2017 it will reduce the level of GFCF across the period by around 1.1% per year. The average impact on quarter-on-quarter GFCF growth is negative 0.02% and the average impact on quarter-on-quarter GDP growth is 0.00%.': 'gdp'
})
gdp_df = gdp_df[~gdp_df['year'].astype(str).str.contains('Q')].copy()
gdp_df['year'] = gdp_df['year'].astype(int)
gdp_df

    year      gdp
0   1948    11429
1   1949    12172
2   1950    12742
3   1951    14305
4   1952    15536
..   ...      ...
73  2021  2322652
74  2022  2580949
75  2023  2752164
76  2024  2890664
77  2025  3037611

[78 rows x 2 columns]

In [49]:
# Combine lending and gdp data
bank_finance_df = pnfcs_annual_df.merge(gdp_df, on='year', how='inner')
bank_finance_df['ratio'] = (bank_finance_df['pnfcs']/bank_finance_df['gdp'])
bank_finance_df['pnfcs'] = bank_finance_df['pnfcs']/1000
bank_finance_df

    year       pnfcs      gdp     ratio
0   1997  167.812500   958539  0.175071
1   1998  171.268333  1002804  0.170789
2   1999  177.936167  1046727  0.169993
3   2000  198.510083  1104759  0.179686
4   2001  222.252667  1150542  0.193172
5   2002  237.096250  1194646  0.198466
6   2003  258.386250  1262502  0.204662
7   2004  271.592667  1327143  0.204645
8   2005  313.206667  1403249  0.223201
9   2006  369.711917  1478080  0.250130
10  2007  424.956167  1551729  0.273860
11  2008  482.378583  1602217  0.301069
12  2009  483.935750  1559405  0.310334
13  2010  450.788417  1615839  0.278981
14  2011  414.224250  1669945  0.248047
15  2012  396.949000  1721708  0.230555
16  2013  375.435333  1789072  0.209849
17  2014  360.163500  1875066  0.192080
18  2015  346.911750  1928016  0.179932
19  2016  352.103000  2004755  0.175634
20  2017  345.769917  2097222  0.164870
21  2018  367.426667  2171559  0.169199
22  2019  389.065583  2252961  0.172691
23  2020  421.944917  2124720  0.198588
24  2021  426.721833  2322652  0.183722
25  2022  428.777000  2580949  0.166132
26  2023  426.918750  2752164  0.155121
27  2024  431.647417  2890664  0.149325
28  2025  456.541250  3037611  0.150296

In [50]:
# Plot line chart
# Base chart
bank_finance_base = alt.Chart(bank_finance_df).encode(
    x=alt.X('year:Q', 
            title='', 
            axis=alt.Axis(
                values=list(range(1997, 2026, 2)),
                format='d',
                labelFontSize=13,
                grid=False))
)

# Line 1: Lending to GDP ratio
bank_finance_line1 = bank_finance_base.mark_line().encode(
    y=alt.Y('ratio:Q',
            title='Lending to GDP ratio',
            scale=alt.Scale(domain=[0.1, 0.4]),
            axis=alt.Axis(
                values=[0.1, 0.2, 0.3, 0.4],
                titleFontSize=13,
                labelFontSize=13,
                titleColor='#e6224b',
                labelColor='#e6224b',
                grid=False))
)

# Line 2: Lending
bank_finance_line2 = bank_finance_base.mark_line(color='#36b7b4').encode(
    y=alt.Y('pnfcs:Q',
            title='Lending (GBP)',
            scale=alt.Scale(domain=[150, 500]),
            axis=alt.Axis(
                values=[150, 300, 450],
                labelExpr='"£" + datum.value + "bn"',
                titleFontSize=13,
                labelFontSize=13,
                titleColor='#36b7b4',
                labelColor='#36b7b4',
                grid=False
            ))
)

bank_finance_line_chart = alt.layer(bank_finance_line1, bank_finance_line2).resolve_scale(
    y='independent'
).properties(
    title=alt.TitleParams(
        ['Source: Bank of England - Database (LPMB6NP); ONS - GDP (YBHA)', 'Note: Net lending is the annual average of monthly amounts outstanding. Ratio is lending divided by annual nominal GDP'],
        orient='bottom',
        fontStyle='italic',
        fontSize=10,
        color='#676A8680',
        fontWeight='normal',
        frame='group',
        dx=0,
        offset=7
    )
)

bank_finance_line_chart

alt.LayerChart(...)

In [51]:
# Load capital markets data
capital_markets_df = pd.read_csv('capital_investment.csv')
breakdown_mapping = {
    'Seed': 'Seed',
    'Start-up and other early stage': 'Early stage',
    'Later stage venture': 'Later stage',
    'ICT (all stages)': 'All stages'
}
capital_markets_df['Breakdown'] = capital_markets_df['Breakdown'].replace(breakdown_mapping)
capital_markets_df['Value'] = capital_markets_df['Value'] * 100
capital_markets_df

,Year,Indicator,ISO,Country,Breakdown,Unit of measure,Value
0,2024,Venture capital investments,USA,United States,Later stage,Share of GDP,28.84
1,2024,Venture capital investments,USA,United States,Early stage,Share of GDP,19.28
2,2024,Venture capital investments,USA,United States,Seed,Share of GDP,5.45
3,2019,Venture capital investments,USA,United States,All stages,Share of GDP,23.24
4,2024,Venture capital investments,GBR,United Kingdom,Later stage,Share of GDP,8.79
5,2024,Venture capital investments,GBR,United Kingdom,Early stage,Share of GDP,7.02
6,2024,Venture capital investments,GBR,United Kingdom,Seed,Share of GDP,1.48
7,2024,Venture capital investments,GBR,United Kingdom,All stages,Share of GDP,8.02

In [52]:
# Plot grouped bar chart
capital_markets_bar_chart = alt.Chart(capital_markets_df).mark_bar().encode(
    y=alt.Y('Value:Q',
            title='Share of GDP',
            axis=alt.Axis(
                values=[0, 10, 20, 30],
                labelExpr= 'datum.value + "%"',
                labelFontSize=13,
                titleFontSize=13,
                grid=False)
            ),
    x=alt.X('Breakdown:N',
            sort=['All stages', 'Seed', 'Early stage', 'Later stage'],
            title='',
            axis=alt.Axis(
                labelFontSize=13,
                titleFontSize=13,
                grid=False)
            ),
    color=alt.Color('Country:N',
                    title='',
                    scale=alt.Scale(domain=['United States', 'United Kingdom']),
                    legend=alt.Legend(
                        orient='none',
                        legendX=10,
                        legendY=10,
                        padding=5,
                        labelFontSize=13)
                    ),
    xOffset=alt.XOffset('Country:N')
)
styles.add_source(capital_markets_bar_chart, 'OECD - Going Digital Toolkit (Indicator 35)')
capital_markets_bar_chart

alt.Chart(...)

In [53]:
# Load investment gap data
invest_gap_df = pd.read_excel('investment_gap.xlsx', sheet_name='Performance (2)', skiprows=5, nrows=21)
invest_gap_df = invest_gap_df[['Industry/Size Band', 'Performance will increase: Point estimate']]
invest_gap_df = invest_gap_df[invest_gap_df['Industry/Size Band'].isin(['0 - 9', '10 - 49', '50 - 99', '100 - 249', '250 +'])]
invest_gap_df['Performance will increase: Point estimate'] = invest_gap_df['Performance will increase: Point estimate'] * 100
invest_gap_df = invest_gap_df.rename(columns={
    'Industry/Size Band': 'size',
    'Performance will increase: Point estimate': 'percentage'
})
size_mapping = {
    '0 - 9': 'Micro\n(0-9)',
    '10 - 49': 'Small\n(10-49)',
    '50 - 99': 'Medium\n(50-99)',
    '100 - 249': 'Medium\n(100-249)',
    '250 +': 'Large\n(250+)'
}
invest_gap_df['size'] = invest_gap_df['size'].replace(size_mapping)
invest_gap_df

                 size percentage
14       Micro\n(0-9)       22.1
15     Small\n(10-49)       30.6
16    Medium\n(50-99)       38.3
17  Medium\n(100-249)       43.1
18      Large\n(250+)       42.5

In [54]:
# Create bar chart
invest_gap_base = alt.Chart(invest_gap_df).encode(
    x=alt.X('size:N',
            sort=['Micro\n(0-9)',
                  'Small\n(10-49)',
                  'Medium\n(50-99)',
                  'Medium\n(100-249)',
                  'Large\n(250+)'],
            title='',
            axis=alt.Axis(
                labelExpr='split(datum.label, "\\n")',
                labelFontSize=13,
                grid=False)
            ),
    y=alt.Y('percentage:Q',
            title='Proportion of businesses expecting performance to increase in next 12 months',
            axis=alt.Axis(
                values=[0, 10, 20, 30, 40, 50],
                labelExpr='datum.value + "%"',
                titleFontSize=13,
                labelFontSize=13,
                grid=False)
            )
)

invest_gap_bar = invest_gap_base.mark_bar()

invest_gap_text = alt.Chart(invest_gap_df).mark_text(
    dx=0, 
    dy=-7, 
    align='center',
    fontSize=14,
    text=alt.expr("format(datum.percentage, '.0f') + '%'")
).encode(
    x=alt.X('size:N', sort=['Micro\n(0-9)', 'Small\n(10-49)', 'Medium\n(50-99)', 'Medium\n(100-249)', 'Large\n(250+)']),
    y='percentage:Q'
)

invest_gap_bar_chart = (invest_gap_bar + invest_gap_text)

styles.add_source(invest_gap_bar_chart, 'ONS - Business Insights and Conditions Survey (Wave 150)')
invest_gap_bar_chart

alt.LayerChart(...)

In [55]:
# Save charts
styles.save(elec_line_chart, 'visualisation', 'elec_line_chart', width=500, height=450)
styles.save(iea_bar_chart, 'visualisation', 'iea_bar_chart', width=500, height=450)
styles.save(sme_barrier_bar_chart, 'visualisation', 'sme_barrier_bar_chart', width=500, height=450)
styles.save(bank_finance_line_chart, 'visualisation', 'bank_finance_line_chart', width=500, height=450)
styles.save(capital_markets_bar_chart, 'visualisation', 'capital_markets_bar_chart', width=500, height=450)
styles.save(invest_gap_bar_chart, 'visualisation', 'invest_gap_bar_chart', width=500, height=450)